export const CIUDADES_POR_PAIS = {
  Paraguay: [
    "Asunción",
    "Ciudad del Este",
    "San Lorenzo",
    "Luque",
    "Capiatá",
    "Lambaré",
    "Fernando de la Mora",
    "Limpio",
    "Ñemby",
    "Encarnación",
    "Pedro Juan Caballero",
    "Coronel Oviedo",
    "Itauguá",
    "Mariano Roque Alonso",
    "Presidente Franco",
    "Villa Elisa",
    "Hernandarias",
    "Concepción",
    "Villarrica",
  ],
  Brasil: [
    "Foz do Iguaçu",
    "Cascavel",
    "Curitiba",
    "São Paulo",
    "Rio de Janeiro",
    "Belo Horizonte",
    "Porto Alegre",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Recife",
    "Manaus",
    "Campinas",
    "Guarulhos",
    "Goiânia",
  ],
};
